spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/miPrimeraapp?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:<<YOUR_PASSWORD>>}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      SensorMovimientoNombreUnique: SENSOR_MOVIMIENTO_NOMBRE_UNIQUE
      SensorTempertauraNombreUnique: SENSOR_TEMPERTAURA_NOMBRE_UNIQUE
      SensorAccesoNombreUnique: SENSOR_ACCESO_NOMBRE_UNIQUE
springdoc:
  pathsToMatch: /api/**
